#ifndef _INTTYPES_H
#define _INTTYPES_H

#include <stdint.h>

/* imaxdiv() result. */
typedef struct {
  intmax_t quot;
  intmax_t rem;
} imaxdiv_t;

intmax_t imaxabs(intmax_t n);
imaxdiv_t imaxdiv(intmax_t num, intmax_t den);
intmax_t strtoimax(const char *s, char **end, int base);
uintmax_t strtoumax(const char *s, char **end, int base);

/* ---- fprintf / fscanf conversion-specifier macros ----------------------
 * ILP32 model: int8_t=signed char, int16_t=short, int32_t=int,
 * int64_t=long long, intptr_t=long, intmax_t=long long; the fast types are
 * all int / long long.  For fprintf the default argument promotions pass
 * 8/16/32-bit values as int, so those take no length modifier; fscanf keys
 * on the target object width (hh / h / none / ll). */
#define __PRI8 ""
#define __PRI16 ""
#define __PRI32 ""
#define __PRI64 "ll"
#define __PRIPTR "l"
#define __SCN8 "hh"
#define __SCN16 "h"
#define __SCN32 ""
#define __SCN64 "ll"
#define __SCNPTR "l"

#define PRId8 __PRI8 "d"
#define PRId16 __PRI16 "d"
#define PRId32 __PRI32 "d"
#define PRId64 __PRI64 "d"
#define PRIdLEAST8 __PRI8 "d"
#define PRIdLEAST16 __PRI16 "d"
#define PRIdLEAST32 __PRI32 "d"
#define PRIdLEAST64 __PRI64 "d"
#define PRIdFAST8 __PRI32 "d"
#define PRIdFAST16 __PRI32 "d"
#define PRIdFAST32 __PRI32 "d"
#define PRIdFAST64 __PRI64 "d"
#define PRIdMAX __PRI64 "d"
#define PRIdPTR __PRIPTR "d"

#define PRIi8 __PRI8 "i"
#define PRIi16 __PRI16 "i"
#define PRIi32 __PRI32 "i"
#define PRIi64 __PRI64 "i"
#define PRIiLEAST8 __PRI8 "i"
#define PRIiLEAST16 __PRI16 "i"
#define PRIiLEAST32 __PRI32 "i"
#define PRIiLEAST64 __PRI64 "i"
#define PRIiFAST8 __PRI32 "i"
#define PRIiFAST16 __PRI32 "i"
#define PRIiFAST32 __PRI32 "i"
#define PRIiFAST64 __PRI64 "i"
#define PRIiMAX __PRI64 "i"
#define PRIiPTR __PRIPTR "i"

#define PRIo8 __PRI8 "o"
#define PRIo16 __PRI16 "o"
#define PRIo32 __PRI32 "o"
#define PRIo64 __PRI64 "o"
#define PRIoLEAST8 __PRI8 "o"
#define PRIoLEAST16 __PRI16 "o"
#define PRIoLEAST32 __PRI32 "o"
#define PRIoLEAST64 __PRI64 "o"
#define PRIoFAST8 __PRI32 "o"
#define PRIoFAST16 __PRI32 "o"
#define PRIoFAST32 __PRI32 "o"
#define PRIoFAST64 __PRI64 "o"
#define PRIoMAX __PRI64 "o"
#define PRIoPTR __PRIPTR "o"

#define PRIu8 __PRI8 "u"
#define PRIu16 __PRI16 "u"
#define PRIu32 __PRI32 "u"
#define PRIu64 __PRI64 "u"
#define PRIuLEAST8 __PRI8 "u"
#define PRIuLEAST16 __PRI16 "u"
#define PRIuLEAST32 __PRI32 "u"
#define PRIuLEAST64 __PRI64 "u"
#define PRIuFAST8 __PRI32 "u"
#define PRIuFAST16 __PRI32 "u"
#define PRIuFAST32 __PRI32 "u"
#define PRIuFAST64 __PRI64 "u"
#define PRIuMAX __PRI64 "u"
#define PRIuPTR __PRIPTR "u"

#define PRIx8 __PRI8 "x"
#define PRIx16 __PRI16 "x"
#define PRIx32 __PRI32 "x"
#define PRIx64 __PRI64 "x"
#define PRIxLEAST8 __PRI8 "x"
#define PRIxLEAST16 __PRI16 "x"
#define PRIxLEAST32 __PRI32 "x"
#define PRIxLEAST64 __PRI64 "x"
#define PRIxFAST8 __PRI32 "x"
#define PRIxFAST16 __PRI32 "x"
#define PRIxFAST32 __PRI32 "x"
#define PRIxFAST64 __PRI64 "x"
#define PRIxMAX __PRI64 "x"
#define PRIxPTR __PRIPTR "x"

#define PRIX8 __PRI8 "X"
#define PRIX16 __PRI16 "X"
#define PRIX32 __PRI32 "X"
#define PRIX64 __PRI64 "X"
#define PRIXLEAST8 __PRI8 "X"
#define PRIXLEAST16 __PRI16 "X"
#define PRIXLEAST32 __PRI32 "X"
#define PRIXLEAST64 __PRI64 "X"
#define PRIXFAST8 __PRI32 "X"
#define PRIXFAST16 __PRI32 "X"
#define PRIXFAST32 __PRI32 "X"
#define PRIXFAST64 __PRI64 "X"
#define PRIXMAX __PRI64 "X"
#define PRIXPTR __PRIPTR "X"

#define SCNd8 __SCN8 "d"
#define SCNd16 __SCN16 "d"
#define SCNd32 __SCN32 "d"
#define SCNd64 __SCN64 "d"
#define SCNdLEAST8 __SCN8 "d"
#define SCNdLEAST16 __SCN16 "d"
#define SCNdLEAST32 __SCN32 "d"
#define SCNdLEAST64 __SCN64 "d"
#define SCNdFAST8 __SCN32 "d"
#define SCNdFAST16 __SCN32 "d"
#define SCNdFAST32 __SCN32 "d"
#define SCNdFAST64 __SCN64 "d"
#define SCNdMAX __SCN64 "d"
#define SCNdPTR __SCNPTR "d"

#define SCNi8 __SCN8 "i"
#define SCNi16 __SCN16 "i"
#define SCNi32 __SCN32 "i"
#define SCNi64 __SCN64 "i"
#define SCNiLEAST8 __SCN8 "i"
#define SCNiLEAST16 __SCN16 "i"
#define SCNiLEAST32 __SCN32 "i"
#define SCNiLEAST64 __SCN64 "i"
#define SCNiFAST8 __SCN32 "i"
#define SCNiFAST16 __SCN32 "i"
#define SCNiFAST32 __SCN32 "i"
#define SCNiFAST64 __SCN64 "i"
#define SCNiMAX __SCN64 "i"
#define SCNiPTR __SCNPTR "i"

#define SCNo8 __SCN8 "o"
#define SCNo16 __SCN16 "o"
#define SCNo32 __SCN32 "o"
#define SCNo64 __SCN64 "o"
#define SCNoLEAST8 __SCN8 "o"
#define SCNoLEAST16 __SCN16 "o"
#define SCNoLEAST32 __SCN32 "o"
#define SCNoLEAST64 __SCN64 "o"
#define SCNoFAST8 __SCN32 "o"
#define SCNoFAST16 __SCN32 "o"
#define SCNoFAST32 __SCN32 "o"
#define SCNoFAST64 __SCN64 "o"
#define SCNoMAX __SCN64 "o"
#define SCNoPTR __SCNPTR "o"

#define SCNu8 __SCN8 "u"
#define SCNu16 __SCN16 "u"
#define SCNu32 __SCN32 "u"
#define SCNu64 __SCN64 "u"
#define SCNuLEAST8 __SCN8 "u"
#define SCNuLEAST16 __SCN16 "u"
#define SCNuLEAST32 __SCN32 "u"
#define SCNuLEAST64 __SCN64 "u"
#define SCNuFAST8 __SCN32 "u"
#define SCNuFAST16 __SCN32 "u"
#define SCNuFAST32 __SCN32 "u"
#define SCNuFAST64 __SCN64 "u"
#define SCNuMAX __SCN64 "u"
#define SCNuPTR __SCNPTR "u"

#define SCNx8 __SCN8 "x"
#define SCNx16 __SCN16 "x"
#define SCNx32 __SCN32 "x"
#define SCNx64 __SCN64 "x"
#define SCNxLEAST8 __SCN8 "x"
#define SCNxLEAST16 __SCN16 "x"
#define SCNxLEAST32 __SCN32 "x"
#define SCNxLEAST64 __SCN64 "x"
#define SCNxFAST8 __SCN32 "x"
#define SCNxFAST16 __SCN32 "x"
#define SCNxFAST32 __SCN32 "x"
#define SCNxFAST64 __SCN64 "x"
#define SCNxMAX __SCN64 "x"
#define SCNxPTR __SCNPTR "x"

#endif /* _INTTYPES_H */
