#!/usr/bin/env pwsh
#
# bootstrap-simenv.ps1 — populate a project-local, self-contained sim68k
# test environment under simenv/ so c68k's CP/M-68K and Osiris tests never
# share the sim binary or the boot/disk images with the sibling worm68k /
# osiris repos.
#
# WHY: a sim68k running out of a shared directory keeps the boot disk
# (scsi0.img) and the disk images open.  A concurrent sim from ANOTHER
# project (e.g. worm68k's _f77sim) then Windows-locks those files and our
# CP/M boot silently fails ("could not open 'scsi0.img'" -> no A>).  And a
# blunt `Get-Process sim68k | Stop-Process` would kill (or be killed by)
# that foreign sim.  Copying every asset locally + renaming our sim to
# c68k-sim68k.exe makes the test rig hermetic: our sim boots from our own
# images, and process cleanup targets ONLY our process name.
#
# The CP/M and Osiris smoke harnesses (tools/run-cpm-smoke.ps1 /
# run-osiris-smoke.ps1) arrive with the OS backends in P4/P5; they boot
# simenv/c68k-sim68k.exe headless and deploy a c68k-built .68K / .PRG.
#
# Copies (idempotent — re-run cheaply; pass -Force for a full refresh):
#   <worm>\68kTools\builds\win64\bin\Release\sim68k.exe -> c68k-sim68k.exe
#   <worm>\68kTools\sim68k\bootrom.bin           -> bootrom.bin           (CP/M + Osiris boot ROM)
#   <worm>\68kTools\sim68k\cpmboot-16mb-144.img  -> cpmboot-16mb-144.img  (CP/M boot floppy A:, 16 MB / 68000 model — default)
#   <worm>\68kTools\sim68k\cpmboot-1mb-144.img   -> cpmboot-1mb-144.img   (CP/M boot floppy A:,  1 MB / 68008 model)
#   <worm>\68kTools\sim68k\scsi0.img             -> scsi0.img             (CP/M C:)
#   <worm>\68kTools\sim68k\scsi1.img          -> scsi1.img        (CP/M D:, deploy target)
#   <osiris>\build\osiris-boot-144.img        -> osiris-boot-144.img (Osiris boot floppy)
#   <worm>\tools\cpmrm.exe                    -> cpmrm.exe        (cpmtools: remove)
#   <worm>\tools\cpmcp.exe                    -> cpmcp.exe        (cpmtools: copy)
#
# Override source repos with -WormRoot / -OsirisRoot or the C68K_WORMROOT
# / C68K_OSIRISROOT environment variables.
#
[CmdletBinding()]
param(
    [string]$WormRoot   = $(if ($env:C68K_WORMROOT)   { $env:C68K_WORMROOT }   else { 'C:\git\worm68k' }),
    [string]$OsirisRoot = $(if ($env:C68K_OSIRISROOT) { $env:C68K_OSIRISROOT } else { 'C:\git\osiris' }),
    [switch]$Force
)
$ErrorActionPreference = 'Stop'
$root   = Split-Path $PSScriptRoot -Parent
$simenv = Join-Path $root 'simenv'
New-Item -ItemType Directory -Force -Path $simenv | Out-Null

$wSim = Join-Path $WormRoot '68kTools\sim68k'
$map = @(
    @{ Src = Join-Path $WormRoot '68kTools\builds\win64\bin\Release\sim68k.exe'; Dst = 'c68k-sim68k.exe' }
    @{ Src = Join-Path $wSim 'bootrom.bin';          Dst = 'bootrom.bin' }
    @{ Src = Join-Path $wSim 'cpmboot-16mb-144.img'; Dst = 'cpmboot-16mb-144.img' }
    @{ Src = Join-Path $wSim 'cpmboot-1mb-144.img';  Dst = 'cpmboot-1mb-144.img' }
    @{ Src = Join-Path $wSim 'scsi0.img';      Dst = 'scsi0.img' }
    @{ Src = Join-Path $wSim 'scsi1.img';      Dst = 'scsi1.img' }
    @{ Src = Join-Path $OsirisRoot 'build\osiris-boot-144.img'; Dst = 'osiris-boot-144.img' }
    @{ Src = Join-Path $WormRoot 'tools\cpmrm.exe'; Dst = 'cpmrm.exe' }
    @{ Src = Join-Path $WormRoot 'tools\cpmcp.exe'; Dst = 'cpmcp.exe' }
)

Write-Host "bootstrap-simenv -> $simenv" -ForegroundColor Cyan
$copied = 0; $skipped = 0; $missing = @()
foreach ($m in $map) {
    $src = $m.Src; $dst = Join-Path $simenv $m.Dst
    if (-not (Test-Path $src)) { $missing += $src; Write-Host "  MISSING source: $src" -ForegroundColor Red; continue }
    $need = $Force -or -not (Test-Path $dst) -or ((Get-Item $src).Length -ne (Get-Item $dst).Length)
    if ($need) {
        Copy-Item $src $dst -Force
        Write-Host ("  copied     {0,-22} {1,12:N0} bytes" -f $m.Dst, (Get-Item $dst).Length) -ForegroundColor Green
        $copied++
    } else {
        Write-Host ("  up-to-date {0}" -f $m.Dst) -ForegroundColor DarkGray
        $skipped++
    }
}

if ($missing.Count) {
    throw "bootstrap-simenv: $($missing.Count) source file(s) missing (see above). Set -WormRoot / -OsirisRoot (or C68K_WORMROOT / C68K_OSIRISROOT)."
}

# provenance stamp (source roots + short hashes) so it's clear what was vendored
$stamp = Join-Path $simenv '.stamp'
$lines = @(
    "# c68k simenv — generated by tools/bootstrap-simenv.ps1",
    "generated : $(Get-Date -Format o)",
    "wormRoot  : $WormRoot",
    "osirisRoot: $OsirisRoot",
    ""
)
foreach ($m in $map) { $lines += ("{0}  {1}" -f (Get-FileHash (Join-Path $simenv $m.Dst)).Hash.Substring(0,16), $m.Dst) }
Set-Content -Path $stamp -Value $lines -Encoding UTF8

Write-Host ("simenv ready (copied {0}, up-to-date {1})" -f $copied, $skipped) -ForegroundColor Cyan
